[2025-05-15T10:14:26.304+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_sales_pipeline.run_dbt_models manual__2025-05-15T10:14:25.440405+00:00 [queued]>
[2025-05-15T10:14:26.310+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_sales_pipeline.run_dbt_models manual__2025-05-15T10:14:25.440405+00:00 [queued]>
[2025-05-15T10:14:26.310+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-05-15T10:14:26.310+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-05-15T10:14:26.310+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-05-15T10:14:26.316+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): run_dbt_models> on 2025-05-15 10:14:25.440405+00:00
[2025-05-15T10:14:26.320+0000] {standard_task_runner.py:55} INFO - Started process 689 to run task
[2025-05-15T10:14:26.323+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_sales_pipeline', 'run_dbt_models', 'manual__2025-05-15T10:14:25.440405+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dbt_pipeline_dag.py', '--cfg-path', '/tmp/tmp11ug8ziz']
[2025-05-15T10:14:26.325+0000] {standard_task_runner.py:83} INFO - Job 14: Subtask run_dbt_models
[2025-05-15T10:14:26.374+0000] {task_command.py:389} INFO - Running <TaskInstance: dbt_sales_pipeline.run_dbt_models manual__2025-05-15T10:14:25.440405+00:00 [running]> on host 1ebbaa439ae5
[2025-05-15T10:14:26.485+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=amina
AIRFLOW_CTX_DAG_ID=dbt_sales_pipeline
AIRFLOW_CTX_TASK_ID=run_dbt_models
AIRFLOW_CTX_EXECUTION_DATE=2025-05-15T10:14:25.440405+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-05-15T10:14:25.440405+00:00
[2025-05-15T10:14:26.486+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-05-15T10:14:26.487+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/dbt && dbt run']
[2025-05-15T10:14:26.493+0000] {subprocess.py:86} INFO - Output:
[2025-05-15T10:14:26.496+0000] {subprocess.py:93} INFO - /bin/bash: line 1: cd: /opt/***/dbt: No such file or directory
[2025-05-15T10:14:26.496+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-15T10:14:26.502+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-15T10:14:26.504+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_sales_pipeline, task_id=run_dbt_models, execution_date=20250515T101425, start_date=20250515T101426, end_date=20250515T101426
[2025-05-15T10:14:26.511+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 14 for task run_dbt_models (Bash command failed. The command returned a non-zero exit code 1.; 689)
[2025-05-15T10:14:26.545+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-05-15T10:14:26.561+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
