[2025-05-15T09:56:54.978+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_sales_pipeline.run_dbt_models scheduled__2025-05-14T00:00:00+00:00 [queued]>
[2025-05-15T09:56:54.983+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_sales_pipeline.run_dbt_models scheduled__2025-05-14T00:00:00+00:00 [queued]>
[2025-05-15T09:56:54.983+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-05-15T09:56:54.983+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2025-05-15T09:56:54.983+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-05-15T09:56:54.989+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): run_dbt_models> on 2025-05-14 00:00:00+00:00
[2025-05-15T09:56:54.991+0000] {standard_task_runner.py:55} INFO - Started process 298 to run task
[2025-05-15T09:56:54.993+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_sales_pipeline', 'run_dbt_models', 'scheduled__2025-05-14T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/dbt_pipeline_dag.py', '--cfg-path', '/tmp/tmp8ri_hvhd']
[2025-05-15T09:56:54.995+0000] {standard_task_runner.py:83} INFO - Job 12: Subtask run_dbt_models
[2025-05-15T09:56:55.035+0000] {task_command.py:389} INFO - Running <TaskInstance: dbt_sales_pipeline.run_dbt_models scheduled__2025-05-14T00:00:00+00:00 [running]> on host 1ebbaa439ae5
[2025-05-15T09:56:55.073+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=amina
AIRFLOW_CTX_DAG_ID=dbt_sales_pipeline
AIRFLOW_CTX_TASK_ID=run_dbt_models
AIRFLOW_CTX_EXECUTION_DATE=2025-05-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-05-14T00:00:00+00:00
[2025-05-15T09:56:55.074+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-05-15T09:56:55.075+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/dbt && dbt run']
[2025-05-15T09:56:55.079+0000] {subprocess.py:86} INFO - Output:
[2025-05-15T09:56:55.081+0000] {subprocess.py:93} INFO - /bin/bash: line 1: cd: /opt/***/dbt: No such file or directory
[2025-05-15T09:56:55.081+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-15T09:56:55.086+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-15T09:56:55.089+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=dbt_sales_pipeline, task_id=run_dbt_models, execution_date=20250514T000000, start_date=20250515T095654, end_date=20250515T095655
[2025-05-15T09:56:55.096+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 12 for task run_dbt_models (Bash command failed. The command returned a non-zero exit code 1.; 298)
[2025-05-15T09:56:55.133+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-05-15T09:56:55.146+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
