[2025-05-15T09:57:17.187+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: load_sales_to_postgres.load_csv manual__2025-05-15T09:52:14.367048+00:00 [queued]>
[2025-05-15T09:57:17.192+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: load_sales_to_postgres.load_csv manual__2025-05-15T09:52:14.367048+00:00 [queued]>
[2025-05-15T09:57:17.192+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-05-15T09:57:17.192+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2025-05-15T09:57:17.192+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-05-15T09:57:17.198+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_csv> on 2025-05-15 09:52:14.367048+00:00
[2025-05-15T09:57:17.200+0000] {standard_task_runner.py:55} INFO - Started process 313 to run task
[2025-05-15T09:57:17.203+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'load_sales_to_postgres', 'load_csv', 'manual__2025-05-15T09:52:14.367048+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/load_sales_to_postgres.py', '--cfg-path', '/tmp/tmp9lbv71xq']
[2025-05-15T09:57:17.204+0000] {standard_task_runner.py:83} INFO - Job 13: Subtask load_csv
[2025-05-15T09:57:17.238+0000] {task_command.py:389} INFO - Running <TaskInstance: load_sales_to_postgres.load_csv manual__2025-05-15T09:52:14.367048+00:00 [running]> on host 1ebbaa439ae5
[2025-05-15T09:57:17.413+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_sales_to_postgres
AIRFLOW_CTX_TASK_ID=load_csv
AIRFLOW_CTX_EXECUTION_DATE=2025-05-15T09:52:14.367048+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-05-15T09:52:14.367048+00:00
[2025-05-15T09:57:17.414+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_sales_to_postgres.py", line 14, in load_csv_to_postgres
    df = pd.read_csv('/opt/airflow/data/sales.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/sales.csv'
[2025-05-15T09:57:17.419+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=load_sales_to_postgres, task_id=load_csv, execution_date=20250515T095214, start_date=20250515T095717, end_date=20250515T095717
[2025-05-15T09:57:17.423+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 13 for task load_csv ([Errno 2] No such file or directory: '/opt/airflow/data/sales.csv'; 313)
[2025-05-15T09:57:17.468+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-05-15T09:57:17.477+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
