[2025-05-15T09:05:14.096+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: load_sales_to_postgres.load_csv scheduled__2025-05-14T00:00:00+00:00 [queued]>
[2025-05-15T09:05:14.100+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: load_sales_to_postgres.load_csv scheduled__2025-05-14T00:00:00+00:00 [queued]>
[2025-05-15T09:05:14.100+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-05-15T09:05:14.100+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-05-15T09:05:14.100+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-05-15T09:05:14.106+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_csv> on 2025-05-14 00:00:00+00:00
[2025-05-15T09:05:14.111+0000] {standard_task_runner.py:55} INFO - Started process 178 to run task
[2025-05-15T09:05:14.114+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'load_sales_to_postgres', 'load_csv', 'scheduled__2025-05-14T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/load_sales_to_postgres.py', '--cfg-path', '/tmp/tmp9he_zycc']
[2025-05-15T09:05:14.115+0000] {standard_task_runner.py:83} INFO - Job 7: Subtask load_csv
[2025-05-15T09:05:14.161+0000] {task_command.py:389} INFO - Running <TaskInstance: load_sales_to_postgres.load_csv scheduled__2025-05-14T00:00:00+00:00 [running]> on host ac250ceb9aa4
[2025-05-15T09:05:14.362+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_sales_to_postgres
AIRFLOW_CTX_TASK_ID=load_csv
AIRFLOW_CTX_EXECUTION_DATE=2025-05-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-05-14T00:00:00+00:00
[2025-05-15T09:05:14.364+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_sales_to_postgres.py", line 14, in load_csv_to_postgres
    df = pd.read_csv('/opt/airflow/data/sales.csv')  # chemin mont√© dans le conteneur Docker
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/sales.csv'
[2025-05-15T09:05:14.368+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=load_sales_to_postgres, task_id=load_csv, execution_date=20250514T000000, start_date=20250515T090514, end_date=20250515T090514
[2025-05-15T09:05:14.373+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 7 for task load_csv ([Errno 2] No such file or directory: '/opt/airflow/data/sales.csv'; 178)
[2025-05-15T09:05:14.418+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-05-15T09:05:14.426+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
